name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: View all directories
      run: ls -ls
    - name: Install Composer
      run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - name: Update
      run: sudo apt-get update
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install Dependencies
      run: composer install --optimize-autoloader --no-dev
    - name: Copy env file
      run: cp .env.example .env
    - name: Generate key
      run: php artisan key:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: vendor/bin/phpunit

  push_to_registry:
    name: Push Docker image to the Github Registry
    runs-on: ubuntu-latest
    needs: [laravel_tests]
    steps:
      - name: Log to the Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
